"""Common DTOs and enums used across the Immich API."""

from enum import Enum
from uuid import UUID

from pydantic import BaseModel, Field


class AlbumUserRole(str, Enum):
    """Album user role."""

    EDITOR = "editor"
    VIEWER = "viewer"


class Permission(str, Enum):
    """API key permission."""

    ALL = "all"
    ACTIVITY_CREATE = "activity.create"
    ACTIVITY_READ = "activity.read"
    ACTIVITY_UPDATE = "activity.update"
    ACTIVITY_DELETE = "activity.delete"
    ACTIVITY_STATISTICS = "activity.statistics"
    APIKEY_CREATE = "apiKey.create"
    APIKEY_READ = "apiKey.read"
    APIKEY_UPDATE = "apiKey.update"
    APIKEY_DELETE = "apiKey.delete"
    ASSET_READ = "asset.read"
    ASSET_UPDATE = "asset.update"
    ASSET_DELETE = "asset.delete"
    ASSET_STATISTICS = "asset.statistics"
    ASSET_SHARE = "asset.share"
    ASSET_VIEW = "asset.view"
    ASSET_DOWNLOAD = "asset.download"
    ASSET_UPLOAD = "asset.upload"
    ASSET_REPLACE = "asset.replace"
    ASSET_COPY = "asset.copy"
    ASSET_DERIVE = "asset.derive"
    ASSET_EDIT_GET = "asset.edit.get"
    ASSET_EDIT_CREATE = "asset.edit.create"
    ASSET_EDIT_DELETE = "asset.edit.delete"
    ALBUM_CREATE = "album.create"
    ALBUM_READ = "album.read"
    ALBUM_UPDATE = "album.update"
    ALBUM_DELETE = "album.delete"
    ALBUM_STATISTICS = "album.statistics"
    ALBUM_SHARE = "album.share"
    ALBUM_DOWNLOAD = "album.download"
    ALBUMASSET_CREATE = "albumAsset.create"
    ALBUMASSET_DELETE = "albumAsset.delete"
    ALBUMUSER_CREATE = "albumUser.create"
    ALBUMUSER_UPDATE = "albumUser.update"
    ALBUMUSER_DELETE = "albumUser.delete"
    AUTH_CHANGEPASSWORD = "auth.changePassword"
    AUTHDEVICE_DELETE = "authDevice.delete"
    ARCHIVE_READ = "archive.read"
    BACKUP_LIST = "backup.list"
    BACKUP_DOWNLOAD = "backup.download"
    BACKUP_UPLOAD = "backup.upload"
    BACKUP_DELETE = "backup.delete"
    DUPLICATE_READ = "duplicate.read"
    DUPLICATE_DELETE = "duplicate.delete"
    FACE_CREATE = "face.create"
    FACE_READ = "face.read"
    FACE_UPDATE = "face.update"
    FACE_DELETE = "face.delete"
    FOLDER_READ = "folder.read"
    JOB_CREATE = "job.create"
    JOB_READ = "job.read"
    LIBRARY_CREATE = "library.create"
    LIBRARY_READ = "library.read"
    LIBRARY_UPDATE = "library.update"
    LIBRARY_DELETE = "library.delete"
    LIBRARY_STATISTICS = "library.statistics"
    TIMELINE_READ = "timeline.read"
    TIMELINE_DOWNLOAD = "timeline.download"
    MAINTENANCE = "maintenance"
    MAP_READ = "map.read"
    MAP_SEARCH = "map.search"
    MEMORY_CREATE = "memory.create"
    MEMORY_READ = "memory.read"
    MEMORY_UPDATE = "memory.update"
    MEMORY_DELETE = "memory.delete"
    MEMORY_STATISTICS = "memory.statistics"
    MEMORYASSET_CREATE = "memoryAsset.create"
    MEMORYASSET_DELETE = "memoryAsset.delete"
    NOTIFICATION_CREATE = "notification.create"
    NOTIFICATION_READ = "notification.read"
    NOTIFICATION_UPDATE = "notification.update"
    NOTIFICATION_DELETE = "notification.delete"
    PARTNER_CREATE = "partner.create"
    PARTNER_READ = "partner.read"
    PARTNER_UPDATE = "partner.update"
    PARTNER_DELETE = "partner.delete"
    PERSON_CREATE = "person.create"
    PERSON_READ = "person.read"
    PERSON_UPDATE = "person.update"
    PERSON_DELETE = "person.delete"
    PERSON_STATISTICS = "person.statistics"
    PERSON_MERGE = "person.merge"
    PERSON_REASSIGN = "person.reassign"
    PINCODE_CREATE = "pinCode.create"
    PINCODE_UPDATE = "pinCode.update"
    PINCODE_DELETE = "pinCode.delete"
    PLUGIN_CREATE = "plugin.create"
    PLUGIN_READ = "plugin.read"
    PLUGIN_UPDATE = "plugin.update"
    PLUGIN_DELETE = "plugin.delete"
    SERVER_ABOUT = "server.about"
    SERVER_APKLINKS = "server.apkLinks"
    SERVER_STORAGE = "server.storage"
    SERVER_STATISTICS = "server.statistics"
    SERVER_VERSIONCHECK = "server.versionCheck"
    SERVERLICENSE_READ = "serverLicense.read"
    SERVERLICENSE_UPDATE = "serverLicense.update"
    SERVERLICENSE_DELETE = "serverLicense.delete"
    SESSION_CREATE = "session.create"
    SESSION_READ = "session.read"
    SESSION_UPDATE = "session.update"
    SESSION_DELETE = "session.delete"
    SESSION_LOCK = "session.lock"
    SHAREDLINK_CREATE = "sharedLink.create"
    SHAREDLINK_READ = "sharedLink.read"
    SHAREDLINK_UPDATE = "sharedLink.update"
    SHAREDLINK_DELETE = "sharedLink.delete"
    STACK_CREATE = "stack.create"
    STACK_READ = "stack.read"
    STACK_UPDATE = "stack.update"
    STACK_DELETE = "stack.delete"
    SYNC_STREAM = "sync.stream"
    SYNCCHECKPOINT_READ = "syncCheckpoint.read"
    SYNCCHECKPOINT_UPDATE = "syncCheckpoint.update"
    SYNCCHECKPOINT_DELETE = "syncCheckpoint.delete"
    SYSTEMCONFIG_READ = "systemConfig.read"
    SYSTEMCONFIG_UPDATE = "systemConfig.update"
    SYSTEMMETADATA_READ = "systemMetadata.read"
    SYSTEMMETADATA_UPDATE = "systemMetadata.update"
    TAG_CREATE = "tag.create"
    TAG_READ = "tag.read"
    TAG_UPDATE = "tag.update"
    TAG_DELETE = "tag.delete"
    TAG_ASSET = "tag.asset"
    USER_READ = "user.read"
    USER_UPDATE = "user.update"
    USERLICENSE_CREATE = "userLicense.create"
    USERLICENSE_READ = "userLicense.read"
    USERLICENSE_UPDATE = "userLicense.update"
    USERLICENSE_DELETE = "userLicense.delete"
    USERONBOARDING_READ = "userOnboarding.read"
    USERONBOARDING_UPDATE = "userOnboarding.update"
    USERONBOARDING_DELETE = "userOnboarding.delete"
    USERPREFERENCE_READ = "userPreference.read"
    USERPREFERENCE_UPDATE = "userPreference.update"
    USERPROFILEIMAGE_CREATE = "userProfileImage.create"
    USERPROFILEIMAGE_READ = "userProfileImage.read"
    USERPROFILEIMAGE_UPDATE = "userProfileImage.update"
    USERPROFILEIMAGE_DELETE = "userProfileImage.delete"
    QUEUE_READ = "queue.read"
    QUEUE_UPDATE = "queue.update"
    QUEUEJOB_CREATE = "queueJob.create"
    QUEUEJOB_READ = "queueJob.read"
    QUEUEJOB_UPDATE = "queueJob.update"
    QUEUEJOB_DELETE = "queueJob.delete"
    WORKFLOW_CREATE = "workflow.create"
    WORKFLOW_READ = "workflow.read"
    WORKFLOW_UPDATE = "workflow.update"
    WORKFLOW_DELETE = "workflow.delete"
    ADMINUSER_CREATE = "adminUser.create"
    ADMINUSER_READ = "adminUser.read"
    ADMINUSER_UPDATE = "adminUser.update"
    ADMINUSER_DELETE = "adminUser.delete"
    ADMINSESSION_READ = "adminSession.read"
    ADMINAUTH_UNLINKALL = "adminAuth.unlinkAll"


class AssetOrder(str, Enum):
    """Asset sort order."""

    ASC = "asc"
    DESC = "desc"


class BulkIdErrorReason(str, Enum):
    """Error reason for bulk operations."""

    DUPLICATE = "duplicate"
    NO_PERMISSION = "no_permission"
    NOT_FOUND = "not_found"
    UNKNOWN = "unknown"


class BulkIdsDto(BaseModel):
    """DTO for bulk operations with a list of IDs."""

    ids: list[UUID] = Field(..., description="IDs to process")


class BulkIdResponseDto(BaseModel):
    """Response item for bulk operations. Uses :class:`BulkIdErrorReason` for error."""

    id: str = Field(..., description="ID")
    success: bool = Field(..., description="Whether operation succeeded")
    error: BulkIdErrorReason | None = Field(None, description="Error reason if failed")


class AssetIdsDto(BaseModel):
    """DTO for a list of asset IDs."""

    assetIds: list[UUID] = Field(..., description="Asset IDs")
